### ISSUE TITLE
Missing "whole.rds" causes failure to run

### ISSUE THREAD

**Issue by vkp3** [andrewhaoyu/PAGEANT#2]
Hello,

I tried running the Shiny tool as specified in the paper and after cloning the code for the shiny app. The shiny app runs, however I run into an issue with the power calculation.
 
Specifically, once I ask it to do the calculation, I am presented with an error that states it is missing a file (`whole.rds`) which I’m assuming is due to a missing RDS that’s required for the tool to run power calculations. It is not included in the github directory – in fact, ‘whole.rds’ seems to be specifically included in the `.gitignore` file, meaning wasn’t uploaded to github (likely due to file size).

I am wondering how I can access this required file so that I can run the app?

I am interested in performing a power analysis for a burden & SKAT-based genetic association test on a UK Biobank data subset (N=~180,000).

Thank you,
Vamsee

**Comment by andrewhaoyu** [comment]
Hi,

I have added the database to git repository. It can be cloned now. Thanks!

Best,
Haoyu

**Comment by vkp3** [comment]
Hi Haoyu,

Thanks for your quick response.

Now it says object `object 'aa' not found`

What could this be?

Vamsee

**Comment by andrewhaoyu** [comment]
Hi Vamsee,

I tried to directly clone the repository and ran the 'example_Rare.r' and 'example_genome_wide.r' codes. But I couldn't reproduce the error message "object 'aa' not found". Can you put the code in the comment so that I can directly reproduce it? Thanks a lot!

Best,
Haoyu

**Comment by vkp3** [comment]
Hi Haoyu,

Once the shiny app is running, when I select 'Quantitative Trait' and enter the following parameters, I get the error with red text on the app that says `Error: object 'aa' not found` in red color text.
The parameters are:

> Type of calculation
> Power Calculation
> Type of power calculation
> Whole Genome
> Total Sample Size: 
> 180256
> α: 
> 0.0000025
> GEV: Genome-wide Variance Explained(Percent) 
> 2
> Method
> Burden Test
> Level of complexity (optional)
> Fast
> Number of causal loci 
> 1000
> Number of discoveries 
> 0
> Proportion of Causal Variants (Optional) 
> Number of Variants (Optional) 


On the console, the following is printed

```
> runApp()

Listening on http://127.0.0.1:6152
Running  1 th EV distribution 
Sol: 0.086 0.005 0.092 0 0 
Running  2 th EV distribution 
Sol: 0.041 0.013 0.053 0 0 
Running  3 th EV distribution 
Sol: 0.035 0.002 0.037 0 0 
Est 1.622 0.033 1.671 0 0 
Warning: Error in calcPower: object 'aa' not found
  154: dbeta [PowerCalc_Rare_whole.r#103]
  153: calcPower [skat_calculator2.r#21]
  152: get_AproxQ2 [PowerCalc_Rare_whole.r#103]
  151: calcGenomeLevel [calc_whole.r#75]
  150: eventReactiveHandler [/Users/vkp/bin/PAGEANT/server.R#332]
  106: data2
  102: exprFunc
  101: widgetFunc
  100: func
   87: origRenderFunc
   86: renderFunc
   82: origRenderFunc
   81: output$values2
    1: runApp
Warning: Error in calcPower: object 'aa' not found
  154: dbeta [PowerCalc_Rare_whole.r#103]
  153: calcPower [skat_calculator2.r#21]
  152: get_AproxQ2 [PowerCalc_Rare_whole.r#103]
  151: calcGenomeLevel [calc_whole.r#75]
  150: eventReactiveHandler [/Users/vkp/bin/PAGEANT/server.R#332]
  106: data2
  102: exprFunc
  101: widgetFunc
  100: func
   87: origRenderFunc
   86: renderFunc
   82: origRenderFunc
   81: output$values2
    1: runApp
```

Thanks for your help,
Vamsee

**Comment by andrewhaoyu** [comment]
Hi Vamsee,

It turns out the current power calculation function doesn't support the burden test. We are working on it to solve this issue. I will let you know as soon as it gets fixed.

Best,
Haoyu

**Comment by andrewhaoyu** [comment]
Hi Vamsee,

We have updated the code to allow burden test to do whole genome power calculations. Compared to the other three tests, burden tests will require too additional essential input parameters: 1) proportion of causal variants; 2) "proportion of protective". You can find the definitions of these parameters in the webpage description. 

Let me know if you have any questions. Thanks!
Best,
Haoyu
